//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientRegistration_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTbl
    {
        public int PatientID { get; set; }
        public string Patient { get; set; }
        public Nullable<long> MRN { get; set; }
        public Nullable<long> CSN { get; set; }
        public string Gender { get; set; }
        public string HomePhone { get; set; }
        public string SSN { get; set; }
        public string PassportNo { get; set; }
        public string LocationCode { get; set; }
        public Nullable<long> LocationID { get; set; }
        public string DOB { get; set; }
        public string UpdateDateTime { get; set; }
    }
}
