//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientRegistration_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceConfiguration
    {
        public int ID { get; set; }
        public string FolderLocation { get; set; }
        public Nullable<int> Timer { get; set; }
    }
}
